live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "MesloLGL Nerd Font"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Escape"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "I"
mods = "Super"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = ""
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = ""
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = ""
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = ""
key = "L"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[shell]
args = ["-l", "-c", "tmux attach || tmux new -s main"]
program = "/bin/zsh"

[window]
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2
